project:
  type: website
website:
  title: "paulbeardactuarial.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About
      - text: Artificial Actuary 
        menu:
          - href: artificial_actuary_cod.qmd
            text: Classifying Causes of Death
  page-footer:
    background: light
    center: 
      - text: "© 2025 Paul Beard"
      - icon: linkedin
        href: https://www.linkedin.com/in/paul-beard-78a420172/
      - icon: github
        href: https://github.com/paulbeardactuarial
format:
  html:
    theme: yeti
    css: 
      - styles.css
      - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
    toc: true