project:
  type: website

website:
  title: "paulbeardactuarial.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Artificial Actuary 
        menu:
          - href: artificial_actuary_cod.qmd
            text: Classifying Causes of Death
        
format:
  html:
    theme: yeti
    css: styles.css
    toc: true



